import Head from 'next/head'
import { Inter } from '@next/font/google'
import AsmaulHusna from './AsmaulHusna';
import Footer from './Footer';

const inter = Inter({ subsets: ['latin'] })

function Home({ datas }) {
  console.log(datas);

  return (
    <>
      <Head >
        <title>Asmaul Husna App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css" />
      </Head>
      <main>
        <div className="container mx-auto my-10">
          <h1
            className="text-4xl text-center font-bold text-gray-800 mb-2"
          >Asmaul Husna <span className='text-red-500 text-4xl'>❤️</span></h1>
          <Footer />
          <div className="flex flex-wrap gap-x-4 justify-center gap-y-2 mt-6">
            {datas.map((data, index) => (
              <AsmaulHusna key={index}
                name={data.name}
                translation={data.transliteration}
                meaning={data.en.meaning}
              />
            ))}
          </div>
        </div>
      </main>

    </>
  )
}

export async function getStaticProps() {
  const res = await fetch('http://api.aladhan.com/asmaAlHusna');
  const data = await res.json();

  return {
    props: { datas: data.data }
  }
}

export default Home;
